name: Create Release

on:
  push:
    tags:
      - '*'  # 当有任何新的 tag 被推送时触发此工作流

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码到工作区

      - name: Generate Changelog
        id: generate-changelog
        run: |
          # 获取上一个标签（如果存在）
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 @^ 2>/dev/null || echo "")
          # 生成变更日志：仅显示 feat/fix 等关键提交
          if [ -z "$PREVIOUS_TAG" ]; then
            COMMITS="首次发布，无历史变更记录。"
          else
            COMMITS=$(git log --pretty=format:"- %s (%h)" $PREVIOUS_TAG..@ --no-merges)
          fi
          # 严格按 GitHub Actions 格式输出
          echo "changelog=$COMMITS" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 推荐使用默认的 GITHUB_TOKEN
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            # 版本说明：${{ github.ref_name }}
            ## 变更日志
            ${{ steps.generate-changelog.outputs.changelog }}  